import Home from '@/page/Home'
import { Metadata } from 'next'
import { customMetadata } from '@/shared/lib/helpers/hook'

export async function generateMetadata(): Promise<Metadata> {
	return customMetadata({
		title: 'Next template',
		description: 'Generated by create next app',
		canonical: 'https://domen.ua/'
	})
}

export default function Root() {
	return (
		<>
			<Home />
		</>
	)
}
